---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr:
# @fonts: 
#-------------------------------------------------------------#

- name: "Register if the support folder exists on the server"
  shell: "ls /support-files/"
  register: exists_support_files
  ignore_errors: true

- name: "Output: The support directory exist?"
  debug:
    msg: "RESULT: {% if exists_support_files.rc == 0 %}Contains.{% else %}Not contain.{% endif %}"

- name: "Output: List contents of support directories"
  debug:
    msg: "RESULT: [{{ exists_support_files.stdout | replace('\n', ',') }}]"
  when: exists_support_files is success

- name: "Custom message"
  set_fact:
    CONST_MSG: "(OS:{{system_current}}) -- {{hello_message}}"

- name: "Output: The message"
  debug:
    msg: "RESULT: {{ CONST_MSG }}"
