---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Default variables to be used in the rule.
# @fonts: 
#-------------------------------------------------------------#

# Current operating system of the environment.
system_current: "{{ env_system | default('coreos') }}"
# Operating system supported by the Role.
system_support_centos: centos
system_support_ubuntu: ubuntu
system_support_coreos: coreos

hello_message: "Message as default value: 'Hello World !!!'"

