---

# DEFAULT VARIABLES: ENVIRONMENT
# #################################################################### #

# Default variable for the entire environment(Inventories, Playbooks, Roles, Tasks).
# Determine the type of Linux environment.
global_system: coreos

# DEFAULT VARIABLES: BLOBAL
# #################################################################### #

# Default variables for the entire environment(Inventories, Playbooks).

# Variables file for Playbooks.
global_vars_files:
  # Public variables to be used in all Tasks and Playbooks.
  public: "{{playbook_dir}}/library/variables/public.yml"
   # Specific variables to a given Linux distribution.
  system: "{{playbook_dir}}/library/variables/support-{{global_system}}.yml"
  # SSH connection variables, for remote access to the machines.
  ssh_initial: "{{inventory_dir}}/connection_vars/ssh_initial.yml"
